package:
  name: rust_matchspec
  version: 0.1.0

source:
  path: ../

build:
  number: 0
  skip: true #[py<37]

requirements:
  build:
    - {{ compiler('rust') }}  # [not win]
    - rust_win-64  # [win]
  host:
    - python
    - maturin
  run:
    - python

test:
  imports:
    - rust_matchspec
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/remkade/matchspec
  license: BSD-3-Clause
  license_file: LICENSE
  summary: A conda matchspec written in Rust
